#KubeJS Dev Properties
#Wed Jul 08 15:23:39 CST 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=false
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
